---
- name: "Copy Nginx configuration for site"
  become: yes
  template:
    src: nginx.conf
    dest: "/etc/nginx/sites-available/{{names_host_name}}"
    mode: u=rw,g=r,o=r
- name: "Create site bundle folder"
  file:
    path: "/home/{{ digitalocean_sudo_user }}/names-bundle"
    state: directory
- name: "Extract site bundle"
  unarchive:
    src: "./temp-names/names-{{ deploy_id }}.tar.gz"
    dest: "/home/{{ digitalocean_sudo_user }}/names-bundle"
- name: "Copy script"
  template:
    src: prepare_files.sh
    dest: "./prepare_files.sh"
    mode: u=rwx,g=rx,o=rx
- name: "Fix permissions and copy static assets to Nginx directory"
  command: "./prepare_files.sh"
  become: yes
- name: Nginx - Restart
  command: "sudo systemctl restart nginx"
  become: yes
