---
- name: Run database init script
  command: "sudo -u postgres psql postgres -f /tmp/init_names_database.sql"
  become: yes
- name: Start service
  shell:
    cmd: "./start.sh"
    chdir: "./names-bundle/server"
  become: no

#- name: "Wait for admin API to become available over http:9001"
#  become: no
#  uri:
#    url: "http://localhost:9001/ping"
#    timeout: 1
#    status_code: [200]
#  retries: 10
#  delay: 5
#  register: admin_api_url_check
#  until: admin_api_url_check['status']|default(0) == 200

- name: "Wait for public API to become available over http:{{ names_port }}"
  become: no
  uri:
    url: "http://localhost:{{ names_port }}/actions/fake-action-boot-test/invocation"
    method: POST
    timeout: 1
    status_code: [404]
  retries: 5
  delay: 5
  register: names_api_url_check
  # Checking for 404 is not the ideal test but at least it verifies that the application is running and is connected to the database.
  until: names_api_url_check['status']|default(0) == 404

#- name: "Check if API is available over http:80 (proxied through Nginx)"
#  become: no
#  uri:
#    url: "http://localhost/api/stats"
#    timeout: 5
#    status_code: [401]

#- name: "Check if HTML is available over http:80 (proxied through Nginx)"
#  become: no
#  uri:
#    url: "http://localhost"
#    timeout: 5
#    status_code: [200]
