---
- name: Start service
  systemd:
    state: started
    name: names
    daemon_reload: yes

- name: "Wait for API to become available over http:{{ names_port }}"
  become: no
  uri:
    url: "http://localhost:{{ names_port }}/admin/ping"
    user: "{{ names_admin_username }}"
    password: "{{ names_admin_password }}"
    force_basic_auth: yes
    timeout: 1
    status_code: 204
  retries: 10
  delay: 10
  register: names_api_url_check
  until: names_api_url_check.status == 204

#- name: "Check if API is available over http:80 (proxied through Nginx)"
#  become: no
#  uri:
#    url: "http://localhost/api/stats"
#    timeout: 5
#    status_code: [401]

#- name: "Check if HTML is available over http:80 (proxied through Nginx)"
#  become: no
#  uri:
#    url: "http://localhost"
#    timeout: 5
#    status_code: [200]
