---
- name: Run database init script
  command: "sudo -u postgres psql postgres -f /tmp/init_names_database.sql"
  become: yes
- name: Start service
  shell:
    cmd: "./start.sh"
    chdir: "./names-bundle/server"
  become: no

#- name: "Wait for admin API to become available over http:9001"
#  become: no
#  uri:
#    url: "http://localhost:9001/ping"
#    timeout: 1
#    status_code: [200]
#  retries: 10
#  delay: 5
#  register: admin_api_url_check
#  until: admin_api_url_check['status']|default(0) == 200

#- name: "Wait for public API to become available over http:8080"
#  become: no
#  uri:
#    url: "http://localhost:8080/api/stats"
#    timeout: 1
#    status_code: [401]
#  retries: 1
#  delay: 5
#  register: public_api_url_check
#  until: public_api_url_check['status']|default(0) == 401 # Yes, 401 is expected but at least it's a proper response

#- name: "Check if API is available over http:80 (proxied through Nginx)"
#  become: no
#  uri:
#    url: "http://localhost/api/stats"
#    timeout: 5
#    status_code: [401]

#- name: "Check if HTML is available over http:80 (proxied through Nginx)"
#  become: no
#  uri:
#    url: "http://localhost"
#    timeout: 5
#    status_code: [200]
