spring:
  profiles:
    active:
      - db
server:
  port: "{{ names_port }}"

actions:
  qrUrlTemplate: "https://namn.mikaelsvensson.info/#/{actionId}"

jwt:
  secret: "{{ names_jwt_secret }}"

facebook:
  secret: "{{ names_facebook_secret }}"