---
- name: "Copy Nginx configuration for site"
  become: yes
  template:
    src: nginx.conf
    dest: "/etc/nginx/sites-available/{{app_host_name}}"
    mode: u=rw,g=r,o=r
- name: "Create site bundle folder"
  file:
    path: "/home/{{ digitalocean_sudo_user }}/achievements-bundle"
    state: directory
- name: Fetch package
  command: "sudo aws s3 cp s3://mikaelsvensson.info-digitalocean.deploy/{{ build_id }}-build/achievements-{{ build_id }}.tar.gz /home/{{ digitalocean_sudo_user }}/achievements-{{ build_id }}.tar.gz"
  become: yes
- name: "Extract site bundle"
  command: "tar -zxvf /home/{{ digitalocean_sudo_user }}/achievements-{{ build_id }}.tar.gz -C /home/{{ digitalocean_sudo_user }}/achievements-bundle"

# Credits: https://computingforgeeks.com/how-to-run-java-jar-application-with-systemd-on-linux/
- name: Create user group for service
  group:
    name: achievements
    system: yes
- name: Create user for service
  user:
    name: achievements
    system: yes
    shell: /bin/false
    create_home: no
    group: achievements
- name: Set service configuration
  template:
    src: achievements_service.conf
    dest: "/etc/systemd/system/achievements.service"
    mode: u=rw,g=r,o=r
  become: yes

- name: "Copy script"
  template:
    src: prepare_files.sh
    dest: "./prepare_files.sh"
    mode: u=rwx,g=rx,o=rx
- name: "Fix permissions and copy static assets to Nginx directory"
  command: "./prepare_files.sh"
  become: yes
- name: Nginx - Restart
  command: "sudo systemctl restart nginx"
  become: yes

- name: Run database init script
  command: "sudo -u postgres psql postgres -f /tmp/init_app_database.sql"
  become: yes
