---
- name: Start service
  command: ./achievements-bundle/server/start.sh
  become: no
  environment:
    PORT: "{{ app_port }}"
    JDBC_DATABASE_URL: "{{ app_jdbc_database_url }}"
    JDBC_DATABASE_USERNAME: "{{ app_db_user_name }}"
    JDBC_DATABASE_PASSWORD: "{{ app_db_user_pw }}"
    GOOGLE_CLIENT_ID: "{{ app_google_client_id }}"
    GOOGLE_CLIENT_SECRET: "{{ app_google_client_secret }}"
    MICROSOFT_CLIENT_ID: "{{ app_microsoft_client_id }}"
    MICROSOFT_CLIENT_SECRET: "{{ app_microsoft_client_secret }}"
    JWT_SIGNING_SECRET: "{{ app_jwt_signing_secret }}"
    SMTP_HOST: "{{ app_smtp_host }}"
    SMTP_PORT: "{{ app_smtp_port }}"
    SMTP_USERNAME: "{{ app_smtp_username }}"
    SMTP_PASSWORD: "{{ app_smtp_password }}"
    SMTP_FROM: "{{ app_smtp_from }}"
    SENTRY_DSN: "{{ app_sentry_dsn }}"
#    - name: Wait for service to respond to /ping (or similar resource)
- name: "Wait for service to become available over http:8080"
  become: no
  uri:
    url: "http://localhost:8080"
    timeout: 5
  retries: 10
  delay: 5
  register: initial_url_check
  until: initial_url_check['status']|default(0) == 200
- name: "Wait for service to become available over http:80"
  become: no
  uri:
    url: "http://localhost"
    timeout: 5
#    - name: Run integration tests
