---
- name: Nginx - Install
  script: "install_nginx.sh"
- name: Nginx - Copy main configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
- name: Nginx - Deleting default configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
# TODO: Configure Nginx with SSL support (certificate from Let's Encrypt). Done?
- name: Nginx - Restart
  command: "sudo systemctl restart nginx"
