---
- name: Nginx - Install
  script: "install_nginx.sh {{ app_host_name }}"
- name: Nginx - Copy configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
# TODO: Configure Nginx with SSL support (certificate from Let's Encrypt)
- name: Nginx - Restart
  script: restart_nginx.sh
