---
- name: Nginx - Install
  script: "install_nginx.sh"
- name: Nginx - Copy main configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0644
# TODO: Configure Nginx with SSL support (certificate from Let's Encrypt). Done?
- name: Nginx - Restart
  script: restart_nginx.sh
