---
- hosts: local
  gather_facts: false
  become: false
  vars:
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
    date_slug_cmd: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    random_string_cmd: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters,digits') }}"
  tasks:
    - name: Set deploy_id
      when: deploy_id is undefined # deploy_id might have been defined using command-line argument
      set_fact:
        deploy_id: "{{ date_slug_cmd }}-{{ random_string_cmd }}"
    - name: Set do_keep_old
      when: do_keep_old is undefined
      set_fact:
        do_keep_old: false

    - debug:
        msg: "build_id is {{ build_id }}. deploy_id is {{ deploy_id }}. backup_id is {{ backup_id }}."

    - name: Get information about floating IP
      uri:
        url: "https://api.digitalocean.com/v2/floating_ips/{{ digitalocean_floating_ip }}"
        method: GET
        headers:
          Authorization: "Bearer {{ digitalocean_api_key }}"
          Content-Type: "application/json"
      register: floating_ip

#    - name: Print stuff
#      debug:
#        msg: "{{ floating_ip }}"

    - name: Get id of Droplet currently assigned to floating IP
      set_fact:
        floating_ip_droplet_id: "{{ floating_ip  | json_query('json.floating_ip.droplet.id') }}"

    - debug:
        msg: "Floating IP {{ digitalocean_floating_ip }} is currently assigned to Droplet {{ floating_ip_droplet_id }}"

    - name: Get information about distributions
      uri:
        url: https://api.digitalocean.com/v2/images?page=1&per_page=1000&type=distribution
        method: GET
        headers:
          Authorization: "Bearer {{ digitalocean_api_key }}"
          Content-Type: "application/json"
      register: distributions

#    - name: Print stuff
#      debug:
#        msg: "{{ distributions }}"

    - name: Get slug of latest Ubuntu distribution
      set_fact:
        # Need to_json and from_json to avoid type checking issue. See https://github.com/ansible/ansible/issues/27299#issuecomment-331068246
        digitalocean_image_id: "{{ distributions | to_json | from_json | json_query('sort_by(json.images[?distribution==`Ubuntu` && contains(regions, `'+digitalocean_region+'`) && contains(slug, `x64`)], &slug)[-1].slug') }}"

    - debug:
        msg: "Image slug for newest Ubuntu distribution is {{ digitalocean_image_id }}"

    - name: Create Droplet from image provided by Digital Ocean.
      digital_ocean:
        state: present
        api_token: "{{ digitalocean_api_key }}"
        backups_enabled: no
        image_id: "{{ digitalocean_image_id }}"
        ipv6: no
        name: "default-{{ deploy_id }}"
        unique_name: yes
        private_networking: yes
        region_id: "{{ digitalocean_region }}"
        size_id: "{{ digitalocean_size_id }}"
        ssh_key_ids: "{{ digitalocean_ssh_pub_keys }}"
        wait: yes
        wait_timeout: 300
        user_data: "{{ lookup('template', 'files/initial_server_setup.sh') }}"
      register: do_droplet

    - name: Read id of new Droplet
      set_fact:
        new_droplet_id: "{{ do_droplet.droplet.id }}"
    - name: Wait for SSH to become available
      pause:
        seconds: 30
    # Source: https://stackoverflow.com/a/35213839
    - name: Remove new Droplet's IP address from list of known hosts in case that address has previous been used by other Droplet
      shell: "ssh-keygen -R {{ do_droplet.droplet.networks.v4[1].ip_address }}"

    - name: Add SSH fingerprint of new Droplet to list of known hosts
      shell: "ssh-keyscan {{ do_droplet.droplet.networks.v4[1].ip_address }} >> {{ ssh_known_hosts_file }}"

    - name: Add host for new Droplet
      add_host:
        hostname: "{{ do_droplet.droplet.networks.v4[1].ip_address }}"
        groupname: digitalocean

- hosts: digitalocean
  gather_facts: false
  remote_user: "{{ digitalocean_sudo_user }}"
  become: true
  vars:
    new_droplet_id: "{{ hostvars[groups['local'][0]].new_droplet_id | default('') }}"
    build_id: "{{ hostvars[groups['local'][0]].build_id }}"
    deploy_id: "{{ hostvars[groups['local'][0]].deploy_id }}"
    backup_id: "{{ hostvars[groups['local'][0]].backup_id }}"
  tasks:
    - debug:
        msg: "build_id is {{ build_id }}. deploy_id is {{ deploy_id }}. backup_id is {{ backup_id }}."
#    - name: Upgrade operating system to latest version. Enable automatic security updates.
    - name: Update package cache
      command: apt update
      become: yes
    - name: Install DigitalOcean Monitoring agent
      include_role:
        name: digitalocean-agent
        tasks_from: install
    - name: Install AWS tooling
      include_role:
        name: aws-tooling
        tasks_from: install
    - name: Install Certbot
      include_role:
        name: certbot
        tasks_from: install
    - name: Install Nginx
      include_role:
        name: nginx
    - name: Install Java
      include_role:
        name: java
    - name: Install PostgreSQL
      include_role:
        name: postgres
    - name: Install Achievements server
      include_role:
        name: achievements
        tasks_from: install
    - name: Install Names server
      include_role:
        name: names
        tasks_from: install
#    - debug:
#        msg: "{{ new_droplet_user_key }}"

    - name: If other Droplet exists; Fetch backups
      command: "sudo aws s3 cp s3://mikaelsvensson.info-digitalocean.deploy/deploy-{{ backup_id }}/ /tmp/ --recursive"
      become: yes
      when: backup_id != ''
    - name: If other Droplet exists; Extract Let's Encrypt backup
      # Source: https://community.letsencrypt.org/t/move-to-another-server/77985/4
      command: "sudo tar -zxvf /tmp/redeploy_backup_{{ backup_id }}_letsencrypt.tar.gz -C /"
      become: yes
      when: backup_id != ''
#    - name: If other Droplet exists; Extract home directory backup
#      command: "sudo tar -zxvf /tmp/redeploy_backup_{{ backup_id }}_homedirectory.tar.gz -C /"
#      become: yes
#      when: backup_id != ''
    - name: If other Droplet exists; Restore database from backup
      shell: "sudo -u postgres psql -f /tmp/redeploy_backup_{{ backup_id }}.sql postgres"
      become: yes
      when: backup_id != ''
    - name: Start Achievements server
      include_role:
        name: achievements
        tasks_from: start
    - name: Start Names server
      include_role:
        name: names
        tasks_from: start
#    - name: Open firewall to allow http, https and ssh to the Droplet.
#    - name: Send status mail
#    - name: If other Droplet exists; Shutdown old Droplet.
#    - name: If other Droplet exists; Take snapshot of old Droplet.
    - name: "Assign floating IP to new Droplet"
      become: no
      digital_ocean_floating_ip:
        state: present
        ip: "{{ digitalocean_floating_ip }}"
        droplet_id: "{{ new_droplet_id }}"
        oauth_token: "{{ digitalocean_api_key }}"
    - name: "Wait for service to become available over http"
      uri:
        url: "http://{{ app_host_name }}"
        timeout: 5
    - name: "Start Certbot for Nginx"
      include_role:
        name: certbot
        tasks_from: start
- hosts: local
  gather_facts: false
  become: false
  vars:
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
  tasks:
    - name: "Wait for service to become available over https"
      uri:
        url: "https://{{ app_host_name }}"
        timeout: 5
#    - name: Wait for DNS change to be propagated, e.g. by waiting for "TTL seconds" (which I believe is 90 seconds for Dynu DNS names)
    # Source: https://stackoverflow.com/a/35213839
    - name: Remove new Droplet's IP address from list of known hosts in case that address has previous been used by other Droplet
      shell: "ssh-keygen -R {{ digitalocean_floating_ip }}"

    - name: Add SSH fingerprint of new Droplet to list of known hosts
      shell: "ssh-keyscan {{ digitalocean_floating_ip }} >> {{ ssh_known_hosts_file }}"

    - name: Delete Droplet previously assigned to the floating IP.
      when:
        - not do_keep_old|bool
        - floating_ip_droplet_id != ''
      digital_ocean:
        state: deleted
        api_token: "{{ digitalocean_api_key }}"
        id: "{{ floating_ip_droplet_id }}"
