---
- name: Postgres - Copy script for setting up database
  template:
    src: init_app_database.sql
    dest: /tmp/init_app_database.sql
    mode: 0666
- name: Postgres - Install
  script: install_postgres.sh
