---
- name: Postgres - Copy install script
  template:
    src: install_postgres.sh
    dest: /root/install_postgres.sh
    mode: 0700
- name: Postgres - Copy script for setting up database
  template:
    src: init_app_database.sql
    dest: /tmp/init_app_database.sql
    mode: 0666
- name: Postgres - Install
  command: /root/install_postgres.sh
